### GET ALL USERS
GET http://localhost:3000/user

### GET ONE USER
GET http://localhost:3000/user/65c664246397478013f9b2f6


### CREATE ADMIN
POST http://localhost:3000/doctor
Content-Type: application/json

{
 "name": "Sergio",
 "surname": "Garcia",
 "age": 21,
 "email": "sergioD@gmail.com",
 "password": "123"
}

### UPDATE USER
PUT http://localhost:3000/user/65c6641c6397478013f9b2f5
Content-Type: application/json

{
 "name": "Sandra",
 "subName": "Garcia",
 "age": 20
}


### DELETE USER
DELETE http://localhost:3000/user/65c6628fd5f4f13719e2c203
